-- Seed CBC report template for specified lab and test group
DO $$
DECLARE
    existing_template_id UUID;
    seeded_template_id UUID;
BEGIN
    SELECT id INTO existing_template_id
    FROM lab_templates
    WHERE lab_id = '2f8d0329-d584-4423-91f6-9ab326b700ae'
      AND template_name = 'CBC Report Template'
    LIMIT 1;

    IF existing_template_id IS NULL THEN
        INSERT INTO lab_templates (
            lab_id,
            template_name,
            template_description,
            test_group_id,
            category,
            gjs_html,
            gjs_css,
            gjs_components,
            gjs_styles,
            gjs_project,
            is_default
        )
        VALUES (
            '2f8d0329-d584-4423-91f6-9ab326b700ae',
            'CBC Report Template',
            'Seeded CBC report layout with reference ranges.',
            '4c1bf546-9764-4d85-9cf7-e9a953b11fbc',
            'reports',
            $$<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>CBC Report</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      color: #333;
      margin: 40px;
    }
    .header { text-align: center; }
    .header h1 { font-size: 32px; margin-bottom: 8px; }
    .header .sub-title { font-size: 18px; margin-bottom: 20px; color: #555; }
    .logo { margin: auto; width: 120px; height: auto; }

    .patient-info, .report-info { margin-bottom: 25px; }
    .patient-info table, .results table { width: 100%; border-collapse: collapse; }
    .patient-info th, .patient-info td, .results th, .results td {
      border: 1px solid #ddd; padding: 8px;
    }
    .results th { background: #f4f4f4; text-align: left; }
    .results td.value { text-align: right; }
    .results .section-row th { background: #fafafa; font-weight: bold; }

    .footer { margin-top: 40px; font-size: 14px; text-align: center; color: #777; }
    .page-break { page-break-after: always; }
    /* Helps GrapesJS recognize inline-editable containers */
    .text-block { display: inline-block; }
  </style>
</head>
<body>

  <div class="header">
    <h1 class="text-3xl md:text-4xl font-medium mb-2 mt-2 text-center text-label">
      <span>Complete Blood Count (CBC) Report</span>
    </h1>
    <div class="sub-title"><span>Generated by Your Lab / Clinic Name</span></div>
    <img class="logo" src="LOGO_SVG_OR_PNG_URL" alt="Lab Logo" />
  </div>

  <div class="patient-info">
    <table>
      <tr>
        <th><span>Patient Name</span></th>
        <td><span>{{patientName}}</span></td>
      </tr>
      <tr>
        <th><span>Age / Sex</span></th>
        <td><span>{{age}} / {{sex}}</span></td>
      </tr>
      <tr>
        <th><span>Unique ID</span></th>
        <td><span>{{patientID}}</span></td>
      </tr>
      <tr>
        <th><span>Sample Collected</span></th>
        <td><span>{{collectionDate}}</span></td>
      </tr>
      <tr>
        <th><span>Report Date</span></th>
        <td><span>{{reportDate}}</span></td>
      </tr>
    </table>
  </div>

  <div class="results">
    <h2><span>Results</span></h2>
    <table>
      <tr>
        <th><span>Test</span></th>
        <th><span>Result</span></th>
        <th><span>Units</span></th>
        <th><span>Reference Range</span></th>
      </tr>

      <!-- Red Cell Indices -->
      <tr class="section-row">
        <th colspan="4"><span>Red Blood Cells</span></th>
      </tr>
      <tr>
        <td><span>Hemoglobin</span></td>
        <td class="value"><span>{{hemoglobin}}</span></td>
        <td><span>g/dL</span></td>
        <td>
          <div class="text-block">
            {% if sex == 'Male' %}
              13.5–17.5
            {% elif sex == 'Female' %}
              12.0–15.5
            {% else %}
              12.0–17.5 (adult)
            {% endif %} g/dL
          </div>
        </td>
      </tr>
      <tr>
        <td><span>Hematocrit (PCV)</span></td>
        <td class="value"><span>{{hematocrit}}</span></td>
        <td><span>%</span></td>
        <td>
          <div class="text-block">
            {% if sex == 'Male' %}
              41–53&nbsp;%
            {% elif sex == 'Female' %}
              36–46&nbsp;%
            {% else %}
              36–53&nbsp;% (adult)
            {% endif %}
          </div>
        </td>
      </tr>
      <tr>
        <td><span>RBC Count</span></td>
        <td class="value"><span>{{rbcCount}}</span></td>
        <td><span>×10<sup>12</sup>/L</span></td>
        <td>
          <div class="text-block">
            {% if sex == 'Male' %}
              4.50–5.90
            {% elif sex == 'Female' %}
              4.10–5.10
            {% else %}
              4.10–5.90 (adult)
            {% endif %} ×10<sup>12</sup>/L
          </div>
        </td>
      </tr>
      <tr>
        <td><span>MCV</span></td>
        <td class="value"><span>{{mcv}}</span></td>
        <td><span>fL</span></td>
        <td><span>80–100</span></td>
      </tr>
      <tr>
        <td><span>MCH</span></td>
        <td class="value"><span>{{mch}}</span></td>
        <td><span>pg</span></td>
        <td><span>27–33</span></td>
      </tr>
      <tr>
        <td><span>MCHC</span></td>
        <td class="value"><span>{{mchc}}</span></td>
        <td><span>g/dL</span></td>
        <td><span>32–36</span></td>
      </tr>
      <tr>
        <td><span>RDW</span></td>
        <td class="value"><span>{{rdw}}</span></td>
        <td><span>%</span></td>
        <td><span>11.5–14.5</span></td>
      </tr>

      <!-- White Cells -->
      <tr class="section-row">
        <th colspan="4"><span>White Blood Cells</span></th>
      </tr>
      <tr>
        <td><span>Total WBC Count (TLC)</span></td>
        <td class="value"><span>{{wbcCount}}</span></td>
        <td><span>×10<sup>9</sup>/L</span></td>
        <td><span>4.0–11.0 ×10<sup>9</sup>/L</span></td>
      </tr>
      <tr>
        <td><span>Neutrophils</span></td>
        <td class="value"><span>{{neutrophilsPct}}</span></td>
        <td><span>%</span></td>
        <td><span>40–70&nbsp;%</span></td>
      </tr>
      <tr>
        <td><span>Lymphocytes</span></td>
        <td class="value"><span>{{lymphocytesPct}}</span></td>
        <td><span>%</span></td>
        <td><span>20–45&nbsp;%</span></td>
      </tr>
      <tr>
        <td><span>Monocytes</span></td>
        <td class="value"><span>{{monocytesPct}}</span></td>
        <td><span>%</span></td>
        <td><span>2–8&nbsp;%</span></td>
      </tr>
      <tr>
        <td><span>Eosinophils</span></td>
        <td class="value"><span>{{eosinophilsPct}}</span></td>
        <td><span>%</span></td>
        <td><span>1–6&nbsp;%</span></td>
      </tr>
      <tr>
        <td><span>Basophils</span></td>
        <td class="value"><span>{{basophilsPct}}</span></td>
        <td><span>%</span></td>
        <td><span>0–1&nbsp;%</span></td>
      </tr>

      <!-- Platelets -->
      <tr class="section-row">
        <th colspan="4"><span>Platelets</span></th>
      </tr>
      <tr>
        <td><span>Platelet Count</span></td>
        <td class="value"><span>{{plateletCount}}</span></td>
        <td><span>×10<sup>9</sup>/L</span></td>
        <td><span>150–450 ×10<sup>9</sup>/L</span></td>
      </tr>
    </table>
  </div>

  <div class="interpretation">
    <h2><span>Interpretation / Notes</span></h2>
    <p><span>{{interpretationNotes}}</span></p>
    <p><span>Reference ranges are for typical non-pregnant adults and may vary by lab and population.</span></p>
  </div>

  <div class="footer">
    <p><span>This is a computer-generated report and does not require a signature.</span></p>
    <p><span>For any queries, contact: lab@example.com | +91-123-456-7890</span></p>
  </div>

  <p class="page-break">&nbsp;</p>
  <span>End of Report</span>

</body>
</html>
$$,
            $$body {
  font-family: Arial, sans-serif;
  color: #333;
  margin: 40px;
}
.header { text-align: center; }
.header h1 { font-size: 32px; margin-bottom: 8px; }
.header .sub-title { font-size: 18px; margin-bottom: 20px; color: #555; }
.logo { margin: auto; width: 120px; height: auto; }

.patient-info, .report-info { margin-bottom: 25px; }
.patient-info table, .results table { width: 100%; border-collapse: collapse; }
.patient-info th, .patient-info td, .results th, .results td {
  border: 1px solid #ddd; padding: 8px;
}
.results th { background: #f4f4f4; text-align: left; }
.results td.value { text-align: right; }
.results .section-row th { background: #fafafa; font-weight: bold; }

.footer { margin-top: 40px; font-size: 14px; text-align: center; color: #777; }
.page-break { page-break-after: always; }
.text-block { display: inline-block; }
$$,
            NULL,
            NULL,
            NULL,
            FALSE
        )
        RETURNING id INTO seeded_template_id;

        INSERT INTO lab_template_versions (
            template_id,
            version_number,
            gjs_html,
            gjs_css,
            gjs_components,
            gjs_styles,
            gjs_project,
            version_name,
            version_notes
        )
        VALUES (
            seeded_template_id,
            1,
            $$<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>CBC Report</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      color: #333;
      margin: 40px;
    }
    .header { text-align: center; }
    .header h1 { font-size: 32px; margin-bottom: 8px; }
    .header .sub-title { font-size: 18px; margin-bottom: 20px; color: #555; }
    .logo { margin: auto; width: 120px; height: auto; }

    .patient-info, .report-info { margin-bottom: 25px; }
    .patient-info table, .results table { width: 100%; border-collapse: collapse; }
    .patient-info th, .patient-info td, .results th, .results td {
      border: 1px solid #ddd; padding: 8px;
    }
    .results th { background: #f4f4f4; text-align: left; }
    .results td.value { text-align: right; }
    .results .section-row th { background: #fafafa; font-weight: bold; }

    .footer { margin-top: 40px; font-size: 14px; text-align: center; color: #777; }
    .page-break { page-break-after: always; }
    /* Helps GrapesJS recognize inline-editable containers */
    .text-block { display: inline-block; }
  </style>
</head>
<body>

  <div class="header">
    <h1 class="text-3xl md:text-4xl font-medium mb-2 mt-2 text-center text-label">
      <span>Complete Blood Count (CBC) Report</span>
    </h1>
    <div class="sub-title"><span>Generated by Your Lab / Clinic Name</span></div>
    <img class="logo" src="LOGO_SVG_OR_PNG_URL" alt="Lab Logo" />
  </div>

  <div class="patient-info">
    <table>
      <tr>
        <th><span>Patient Name</span></th>
        <td><span>{{patientName}}</span></td>
      </tr>
      <tr>
        <th><span>Age / Sex</span></th>
        <td><span>{{age}} / {{sex}}</span></td>
      </tr>
      <tr>
        <th><span>Unique ID</span></th>
        <td><span>{{patientID}}</span></td>
      </tr>
      <tr>
        <th><span>Sample Collected</span></th>
        <td><span>{{collectionDate}}</span></td>
      </tr>
      <tr>
        <th><span>Report Date</span></th>
        <td><span>{{reportDate}}</span></td>
      </tr>
    </table>
  </div>

  <div class="results">
    <h2><span>Results</span></h2>
    <table>
      <tr>
        <th><span>Test</span></th>
        <th><span>Result</span></th>
        <th><span>Units</span></th>
        <th><span>Reference Range</span></th>
      </tr>

      <!-- Red Cell Indices -->
      <tr class="section-row">
        <th colspan="4"><span>Red Blood Cells</span></th>
      </tr>
      <tr>
        <td><span>Hemoglobin</span></td>
        <td class="value"><span>{{hemoglobin}}</span></td>
        <td><span>g/dL</span></td>
        <td>
          <div class="text-block">
            {% if sex == 'Male' %}
              13.5–17.5
            {% elif sex == 'Female' %}
              12.0–15.5
            {% else %}
              12.0–17.5 (adult)
            {% endif %} g/dL
          </div>
        </td>
      </tr>
      <tr>
        <td><span>Hematocrit (PCV)</span></td>
        <td class="value"><span>{{hematocrit}}</span></td>
        <td><span>%</span></td>
        <td>
          <div class="text-block">
            {% if sex == 'Male' %}
              41–53&nbsp;%
            {% elif sex == 'Female' %}
              36–46&nbsp;%
            {% else %}
              36–53&nbsp;% (adult)
            {% endif %}
          </div>
        </td>
      </tr>
      <tr>
        <td><span>RBC Count</span></td>
        <td class="value"><span>{{rbcCount}}</span></td>
        <td><span>×10<sup>12</sup>/L</span></td>
        <td>
          <div class="text-block">
            {% if sex == 'Male' %}
              4.50–5.90
            {% elif sex == 'Female' %}
              4.10–5.10
            {% else %}
              4.10–5.90 (adult)
            {% endif %} ×10<sup>12</sup>/L
          </div>
        </td>
      </tr>
      <tr>
        <td><span>MCV</span></td>
        <td class="value"><span>{{mcv}}</span></td>
        <td><span>fL</span></td>
        <td><span>80–100</span></td>
      </tr>
      <tr>
        <td><span>MCH</span></td>
        <td class="value"><span>{{mch}}</span></td>
        <td><span>pg</span></td>
        <td><span>27–33</span></td>
      </tr>
      <tr>
        <td><span>MCHC</span></td>
        <td class="value"><span>{{mchc}}</span></td>
        <td><span>g/dL</span></td>
        <td><span>32–36</span></td>
      </tr>
      <tr>
        <td><span>RDW</span></td>
        <td class="value"><span>{{rdw}}</span></td>
        <td><span>%</span></td>
        <td><span>11.5–14.5</span></td>
      </tr>

      <!-- White Cells -->
      <tr class="section-row">
        <th colspan="4"><span>White Blood Cells</span></th>
      </tr>
      <tr>
        <td><span>Total WBC Count (TLC)</span></td>
        <td class="value"><span>{{wbcCount}}</span></td>
        <td><span>×10<sup>9</sup>/L</span></td>
        <td><span>4.0–11.0 ×10<sup>9</sup>/L</span></td>
      </tr>
      <tr>
        <td><span>Neutrophils</span></td>
        <td class="value"><span>{{neutrophilsPct}}</span></td>
        <td><span>%</span></td>
        <td><span>40–70&nbsp;%</span></td>
      </tr>
      <tr>
        <td><span>Lymphocytes</span></td>
        <td class="value"><span>{{lymphocytesPct}}</span></td>
        <td><span>%</span></td>
        <td><span>20–45&nbsp;%</span></td>
      </tr>
      <tr>
        <td><span>Monocytes</span></td>
        <td class="value"><span>{{monocytesPct}}</span></td>
        <td><span>%</span></td>
        <td><span>2–8&nbsp;%</span></td>
      </tr>
      <tr>
        <td><span>Eosinophils</span></td>
        <td class="value"><span>{{eosinophilsPct}}</span></td>
        <td><span>%</span></td>
        <td><span>1–6&nbsp;%</span></td>
      </tr>
      <tr>
        <td><span>Basophils</span></td>
        <td class="value"><span>{{basophilsPct}}</span></td>
        <td><span>%</span></td>
        <td><span>0–1&nbsp;%</span></td>
      </tr>

      <!-- Platelets -->
      <tr class="section-row">
        <th colspan="4"><span>Platelets</span></th>
      </tr>
      <tr>
        <td><span>Platelet Count</span></td>
        <td class="value"><span>{{plateletCount}}</span></td>
        <td><span>×10<sup>9</sup>/L</span></td>
        <td><span>150–450 ×10<sup>9</sup>/L</span></td>
      </tr>
    </table>
  </div>

  <div class="interpretation">
    <h2><span>Interpretation / Notes</span></h2>
    <p><span>{{interpretationNotes}}</span></p>
    <p><span>Reference ranges are for typical non-pregnant adults and may vary by lab and population.</span></p>
  </div>

  <div class="footer">
    <p><span>This is a computer-generated report and does not require a signature.</span></p>
    <p><span>For any queries, contact: lab@example.com | +91-123-456-7890</span></p>
  </div>

  <p class="page-break">&nbsp;</p>
  <span>End of Report</span>

</body>
</html>
$$,
            $$body {
  font-family: Arial, sans-serif;
  color: #333;
  margin: 40px;
}
.header { text-align: center; }
.header h1 { font-size: 32px; margin-bottom: 8px; }
.header .sub-title { font-size: 18px; margin-bottom: 20px; color: #555; }
.logo { margin: auto; width: 120px; height: auto; }

.patient-info, .report-info { margin-bottom: 25px; }
.patient-info table, .results table { width: 100%; border-collapse: collapse; }
.patient-info th, .patient-info td, .results th, .results td {
  border: 1px solid #ddd; padding: 8px;
}
.results th { background: #f4f4f4; text-align: left; }
.results td.value { text-align: right; }
.results .section-row th { background: #fafafa; font-weight: bold; }

.footer { margin-top: 40px; font-size: 14px; text-align: center; color: #777; }
.page-break { page-break-after: always; }
.text-block { display: inline-block; }
$$,
            NULL,
            NULL,
            NULL,
            'Initial',
            'Seeded CBC report template version 1.'
        );

    ELSE
        seeded_template_id := existing_template_id;

        IF NOT EXISTS (
            SELECT 1
            FROM lab_template_versions
            WHERE template_id = seeded_template_id
              AND version_number = 1
        ) THEN
            INSERT INTO lab_template_versions (
                template_id,
                version_number,
                gjs_html,
                gjs_css,
                gjs_components,
                gjs_styles,
                gjs_project,
                version_name,
                version_notes
            )
            VALUES (
                seeded_template_id,
                1,
                $$<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>CBC Report</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      color: #333;
      margin: 40px;
    }
    .header { text-align: center; }
    .header h1 { font-size: 32px; margin-bottom: 8px; }
    .header .sub-title { font-size: 18px; margin-bottom: 20px; color: #555; }
    .logo { margin: auto; width: 120px; height: auto; }

    .patient-info, .report-info { margin-bottom: 25px; }
    .patient-info table, .results table { width: 100%; border-collapse: collapse; }
    .patient-info th, .patient-info td, .results th, .results td {
      border: 1px solid #ddd; padding: 8px;
    }
    .results th { background: #f4f4f4; text-align: left; }
    .results td.value { text-align: right; }
    .results .section-row th { background: #fafafa; font-weight: bold; }

    .footer { margin-top: 40px; font-size: 14px; text-align: center; color: #777; }
    .page-break { page-break-after: always; }
    /* Helps GrapesJS recognize inline-editable containers */
    .text-block { display: inline-block; }
  </style>
</head>
<body>

  <div class="header">
    <h1 class="text-3xl md:text-4xl font-medium mb-2 mt-2 text-center text-label">
      <span>Complete Blood Count (CBC) Report</span>
    </h1>
    <div class="sub-title"><span>Generated by Your Lab / Clinic Name</span></div>
    <img class="logo" src="LOGO_SVG_OR_PNG_URL" alt="Lab Logo" />
  </div>

  <div class="patient-info">
    <table>
      <tr>
        <th><span>Patient Name</span></th>
        <td><span>{{patientName}}</span></td>
      </tr>
      <tr>
        <th><span>Age / Sex</span></th>
        <td><span>{{age}} / {{sex}}</span></td>
      </tr>
      <tr>
        <th><span>Unique ID</span></th>
        <td><span>{{patientID}}</span></td>
      </tr>
      <tr>
        <th><span>Sample Collected</span></th>
        <td><span>{{collectionDate}}</span></td>
      </tr>
      <tr>
        <th><span>Report Date</span></th>
        <td><span>{{reportDate}}</span></td>
      </tr>
    </table>
  </div>

  <div class="results">
    <h2><span>Results</span></h2>
    <table>
      <tr>
        <th><span>Test</span></th>
        <th><span>Result</span></th>
        <th><span>Units</span></th>
        <th><span>Reference Range</span></th>
      </tr>

      <!-- Red Cell Indices -->
      <tr class="section-row">
        <th colspan="4"><span>Red Blood Cells</span></th>
      </tr>
      <tr>
        <td><span>Hemoglobin</span></td>
        <td class="value"><span>{{hemoglobin}}</span></td>
        <td><span>g/dL</span></td>
        <td>
          <div class="text-block">
            {% if sex == 'Male' %}
              13.5–17.5
            {% elif sex == 'Female' %}
              12.0–15.5
            {% else %}
              12.0–17.5 (adult)
            {% endif %} g/dL
          </div>
        </td>
      </tr>
      <tr>
        <td><span>Hematocrit (PCV)</span></td>
        <td class="value"><span>{{hematocrit}}</span></td>
        <td><span>%</span></td>
        <td>
          <div class="text-block">
            {% if sex == 'Male' %}
              41–53&nbsp;%
            {% elif sex == 'Female' %}
              36–46&nbsp;%
            {% else %}
              36–53&nbsp;% (adult)
            {% endif %}
          </div>
        </td>
      </tr>
      <tr>
        <td><span>RBC Count</span></td>
        <td class="value"><span>{{rbcCount}}</span></td>
        <td><span>×10<sup>12</sup>/L</span></td>
        <td>
          <div class="text-block">
            {% if sex == 'Male' %}
              4.50–5.90
            {% elif sex == 'Female' %}
              4.10–5.10
            {% else %}
              4.10–5.90 (adult)
            {% endif %} ×10<sup>12</sup>/L
          </div>
        </td>
      </tr>
      <tr>
        <td><span>MCV</span></td>
        <td class="value"><span>{{mcv}}</span></td>
        <td><span>fL</span></td>
        <td><span>80–100</span></td>
      </tr>
      <tr>
        <td><span>MCH</span></td>
        <td class="value"><span>{{mch}}</span></td>
        <td><span>pg</span></td>
        <td><span>27–33</span></td>
      </tr>
      <tr>
        <td><span>MCHC</span></td>
        <td class="value"><span>{{mchc}}</span></td>
        <td><span>g/dL</span></td>
        <td><span>32–36</span></td>
      </tr>
      <tr>
        <td><span>RDW</span></td>
        <td class="value"><span>{{rdw}}</span></td>
        <td><span>%</span></td>
        <td><span>11.5–14.5</span></td>
      </tr>

      <!-- White Cells -->
      <tr class="section-row">
        <th colspan="4"><span>White Blood Cells</span></th>
      </tr>
      <tr>
        <td><span>Total WBC Count (TLC)</span></td>
        <td class="value"><span>{{wbcCount}}</span></td>
        <td><span>×10<sup>9</sup>/L</span></td>
        <td><span>4.0–11.0 ×10<sup>9</sup>/L</span></td>
      </tr>
      <tr>
        <td><span>Neutrophils</span></td>
        <td class="value"><span>{{neutrophilsPct}}</span></td>
        <td><span>%</span></td>
        <td><span>40–70&nbsp;%</span></td>
      </tr>
      <tr>
        <td><span>Lymphocytes</span></td>
        <td class="value"><span>{{lymphocytesPct}}</span></td>
        <td><span>%</span></td>
        <td><span>20–45&nbsp;%</span></td>
      </tr>
      <tr>
        <td><span>Monocytes</span></td>
        <td class="value"><span>{{monocytesPct}}</span></td>
        <td><span>%</span></td>
        <td><span>2–8&nbsp;%</span></td>
      </tr>
      <tr>
        <td><span>Eosinophils</span></td>
        <td class="value"><span>{{eosinophilsPct}}</span></td>
        <td><span>%</span></td>
        <td><span>1–6&nbsp;%</span></td>
      </tr>
      <tr>
        <td><span>Basophils</span></td>
        <td class="value"><span>{{basophilsPct}}</span></td>
        <td><span>%</span></td>
        <td><span>0–1&nbsp;%</span></td>
      </tr>

      <!-- Platelets -->
      <tr class="section-row">
        <th colspan="4"><span>Platelets</span></th>
      </tr>
      <tr>
        <td><span>Platelet Count</span></td>
        <td class="value"><span>{{plateletCount}}</span></td>
        <td><span>×10<sup>9</sup>/L</span></td>
        <td><span>150–450 ×10<sup>9</sup>/L</span></td>
      </tr>
    </table>
  </div>

  <div class="interpretation">
    <h2><span>Interpretation / Notes</span></h2>
    <p><span>{{interpretationNotes}}</span></p>
    <p><span>Reference ranges are for typical non-pregnant adults and may vary by lab and population.</span></p>
  </div>

  <div class="footer">
    <p><span>This is a computer-generated report and does not require a signature.</span></p>
    <p><span>For any queries, contact: lab@example.com | +91-123-456-7890</span></p>
  </div>

  <p class="page-break">&nbsp;</p>
  <span>End of Report</span>

</body>
</html>
$$,
                $$body {
  font-family: Arial, sans-serif;
  color: #333;
  margin: 40px;
}
.header { text-align: center; }
.header h1 { font-size: 32px; margin-bottom: 8px; }
.header .sub-title { font-size: 18px; margin-bottom: 20px; color: #555; }
.logo { margin: auto; width: 120px; height: auto; }

.patient-info, .report-info { margin-bottom: 25px; }
.patient-info table, .results table { width: 100%; border-collapse: collapse; }
.patient-info th, .patient-info td, .results th, .results td {
  border: 1px solid #ddd; padding: 8px;
}
.results th { background: #f4f4f4; text-align: left; }
.results td.value { text-align: right; }
.results .section-row th { background: #fafafa; font-weight: bold; }

.footer { margin-top: 40px; font-size: 14px; text-align: center; color: #777; }
.page-break { page-break-after: always; }
.text-block { display: inline-block; }
$$,
                NULL,
                NULL,
                NULL,
                'Initial',
                'Backfilled CBC report template version.'
            );
        END IF;
    END IF;
END $$;