-- Accession/pre-barcoded sample support with lab-scoped barcode uniqueness.
-- Keeps sample_transits as the batch item table; sample_batches is only the header.

ALTER TABLE public.samples
  ADD COLUMN IF NOT EXISTS pre_barcoded boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS barcode_source text NOT NULL DEFAULT 'generated',
  ADD COLUMN IF NOT EXISTS barcode_assigned_at timestamptz,
  ADD COLUMN IF NOT EXISTS barcode_assigned_by uuid REFERENCES public.users(id);

ALTER TABLE public.samples
  DROP CONSTRAINT IF EXISTS samples_barcode_source_check;

ALTER TABLE public.samples
  ADD CONSTRAINT samples_barcode_source_check
  CHECK (barcode_source IN ('generated', 'preprinted', 'manual'));

COMMENT ON COLUMN public.samples.pre_barcoded IS
'True when the physical tube already had a barcode before order/sample creation.';

COMMENT ON COLUMN public.samples.barcode_source IS
'Barcode origin: generated by LIMS, preprinted before registration, or manually assigned.';

COMMENT ON COLUMN public.samples.barcode_assigned_at IS
'Timestamp when the barcode value was assigned to this sample record.';

COMMENT ON COLUMN public.samples.barcode_assigned_by IS
'User who assigned or scanned the barcode value, when known.';

CREATE UNIQUE INDEX IF NOT EXISTS idx_samples_lab_barcode_unique
ON public.samples(lab_id, barcode)
WHERE lab_id IS NOT NULL
  AND barcode IS NOT NULL
  AND btrim(barcode) <> '';

CREATE TABLE IF NOT EXISTS public.sample_batches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lab_id uuid NOT NULL REFERENCES public.labs(id) ON DELETE CASCADE,
  batch_number text NOT NULL,
  from_location_id uuid REFERENCES public.locations(id) ON DELETE SET NULL,
  to_location_id uuid REFERENCES public.locations(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'created'
    CHECK (status IN ('created', 'ready_for_dispatch', 'in_transit', 'received', 'partially_received', 'cancelled')),
  created_by uuid REFERENCES public.users(id) ON DELETE SET NULL,
  dispatched_at timestamptz,
  dispatched_by uuid REFERENCES public.users(id) ON DELETE SET NULL,
  received_at timestamptz,
  received_by uuid REFERENCES public.users(id) ON DELETE SET NULL,
  notes text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sample_batches_pkey PRIMARY KEY (id),
  CONSTRAINT sample_batches_lab_batch_number_key UNIQUE (lab_id, batch_number)
);

CREATE INDEX IF NOT EXISTS idx_sample_batches_lab_status
ON public.sample_batches(lab_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_sample_transits_batch_id
ON public.sample_transits(batch_id)
WHERE batch_id IS NOT NULL;

-- Existing sample_transits rows may already have batch_id values from the
-- earlier transit workflow. Create header rows for those batches before adding
-- the FK so historical transit data remains valid.
INSERT INTO public.sample_batches (
  id,
  lab_id,
  batch_number,
  from_location_id,
  to_location_id,
  status,
  created_at,
  updated_at,
  metadata
)
SELECT
  st.batch_id,
  st.lab_id,
  'MIG-' || st.batch_id::text AS batch_number,
  (array_agg(st.from_location_id ORDER BY st.created_at))[1] AS from_location_id,
  (array_agg(st.to_location_id ORDER BY st.created_at))[1] AS to_location_id,
  CASE
    WHEN bool_and(st.status = 'received') THEN 'received'
    WHEN bool_or(st.status IN ('in_transit', 'delivered')) THEN 'in_transit'
    ELSE 'created'
  END AS status,
  min(st.created_at) AS created_at,
  now() AS updated_at,
  jsonb_build_object('source', 'migrated_from_sample_transits')
FROM public.sample_transits st
WHERE st.batch_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM public.sample_batches sb
    WHERE sb.id = st.batch_id
  )
GROUP BY st.batch_id, st.lab_id;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'sample_transits_batch_id_fkey'
      AND conrelid = 'public.sample_transits'::regclass
  ) THEN
    ALTER TABLE public.sample_transits
      ADD CONSTRAINT sample_transits_batch_id_fkey
      FOREIGN KEY (batch_id) REFERENCES public.sample_batches(id) ON DELETE SET NULL;
  END IF;
END;
$$;

ALTER TABLE public.sample_batches ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Sample batches are viewable by users in same lab" ON public.sample_batches;
CREATE POLICY "Sample batches are viewable by users in same lab"
ON public.sample_batches FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.users u
    WHERE u.id = auth.uid()
      AND u.lab_id = sample_batches.lab_id
  )
);

DROP POLICY IF EXISTS "Sample batches are insertable by users in same lab" ON public.sample_batches;
CREATE POLICY "Sample batches are insertable by users in same lab"
ON public.sample_batches FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.users u
    WHERE u.id = auth.uid()
      AND u.lab_id = sample_batches.lab_id
  )
);

DROP POLICY IF EXISTS "Sample batches are updatable by users in same lab" ON public.sample_batches;
CREATE POLICY "Sample batches are updatable by users in same lab"
ON public.sample_batches FOR UPDATE
USING (
  EXISTS (
    SELECT 1 FROM public.users u
    WHERE u.id = auth.uid()
      AND u.lab_id = sample_batches.lab_id
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.users u
    WHERE u.id = auth.uid()
      AND u.lab_id = sample_batches.lab_id
  )
);

COMMENT ON TABLE public.sample_batches IS
'Accession/dispatch batch header for grouping sample_transits rows sent from collection to processing.';

COMMENT ON COLUMN public.sample_transits.batch_id IS
'Optional accession/dispatch batch header for grouped sample movement.';
